export type RoadmapStage = {
  id: string;
  phase: number;
  title: string;
  titleKh: string;
  window: string;
  focus: string;
  focusKh: string;
  topics: { name: string; icon: string; desc: string }[];
  outcomes: string[];
  outcomesKh: string[];
  project: string;
  projectKh: string;
  color: string;
  resources: { label: string; url: string }[];
};

export type RoadmapPath = {
  id: "frontend" | "backend" | "fullstack";
  label: string;
  labelKh: string;
  tagline: string;
  taglineKh: string;
  icon: string;
  accent: string;
  gradient: string;
  stages: RoadmapStage[];
};

export const roadmapPaths: RoadmapPath[] = [
  {
    id: "frontend",
    label: "Frontend",
    labelKh: "ផ្នែកមុខ",
    tagline: "Build beautiful, responsive user interfaces",
    taglineKh: "បង្កើត UI ស្អាត responsive សម្រាប់គ្រប់ឧបករណ៍",
    icon: "🖥️",
    accent: "blue",
    gradient: "from-blue-600 to-sky-500",
    stages: [
      {
        id: "fe-1",
        phase: 1,
        title: "Web Foundations",
        titleKh: "មូលដ្ឋានគ្រឹះ Web",
        window: "ខែ 1–2",
        focus: "Master HTML structure, CSS styling and layout systems before touching JavaScript.",
        focusKh: "រៀន HTML, CSS, Flexbox, Grid Layout ជំហានដំបូង",
        topics: [
          { name: "HTML5 Semantics", icon: "🌐", desc: "Tags, forms, accessibility, SEO" },
          { name: "CSS Fundamentals", icon: "🎨", desc: "Selectors, box model, typography" },
          { name: "Flexbox & Grid", icon: "⬜", desc: "Modern layout systems" },
          { name: "Responsive Design", icon: "📱", desc: "Media queries, mobile-first" },
          { name: "Git & GitHub", icon: "🔁", desc: "Version control basics" },
        ],
        outcomes: [
          "Build any static webpage from a design mockup",
          "Write semantic, accessible HTML",
          "Create responsive layouts with Flexbox and Grid",
          "Use Git for version control",
        ],
        outcomesKh: [
          "បង្កើតទំព័រ static ពី design",
          "សរសេរ HTML semantic ត្រឹមត្រូវ",
          "ប្រើ Flexbox/Grid Layout",
          "ប្រើ Git សម្រាប់ version control",
        ],
        project: "Personal Portfolio Website — responsive, multi-section, deployed to GitHub Pages",
        projectKh: "គេហទំព័រ Portfolio ផ្ទាល់ខ្លួន — responsive, deploy ទៅ GitHub Pages",
        color: "from-orange-500 to-pink-500",
        resources: [
          { label: "MDN Web Docs", url: "https://developer.mozilla.org" },
          { label: "CSS Tricks", url: "https://css-tricks.com" },
        ],
      },
      {
        id: "fe-2",
        phase: 2,
        title: "JavaScript Mastery",
        titleKh: "JavaScript ស៊ីជម្រៅ",
        window: "ខែ 2–4",
        focus: "Learn JavaScript from variables to async programming and DOM manipulation.",
        focusKh: "រៀន JavaScript ពី Variables រហូតដល់ Async/Await និង DOM",
        topics: [
          { name: "JS Core", icon: "⚡", desc: "Variables, functions, arrays, objects" },
          { name: "DOM Manipulation", icon: "🌳", desc: "Events, selectors, dynamic content" },
          { name: "ES6+ Features", icon: "✨", desc: "Arrow functions, destructuring, modules" },
          { name: "Async JavaScript", icon: "⏳", desc: "Promises, async/await, fetch API" },
          { name: "TypeScript Basics", icon: "🔷", desc: "Types, interfaces, generics" },
        ],
        outcomes: [
          "Write clean JavaScript with ES6+ syntax",
          "Manipulate the DOM dynamically",
          "Fetch and display data from APIs",
          "Understand TypeScript fundamentals",
        ],
        outcomesKh: [
          "សរសេរ JavaScript ស្អាតជាមួយ ES6+",
          "Manipulate DOM dynamically",
          "Fetch data ពី API",
          "យល់ TypeScript",
        ],
        project: "Weather Dashboard App — fetches real API data, dynamic UI updates",
        projectKh: "App ព្យាករណ៍អាកាសធាតុ — fetch real API, UI dynamic",
        color: "from-yellow-400 to-orange-500",
        resources: [
          { label: "JavaScript.info", url: "https://javascript.info" },
          { label: "TypeScript Docs", url: "https://typescriptlang.org" },
        ],
      },
      {
        id: "fe-3",
        phase: 3,
        title: "React & Modern UI",
        titleKh: "React & UI ទំនើប",
        window: "ខែ 4–6",
        focus: "Build component-based UIs with React, manage state, and integrate with APIs.",
        focusKh: "បង្កើត UI ជាមួយ React Components, State, Hooks, Routing",
        topics: [
          { name: "React Components", icon: "⚛️", desc: "JSX, props, component patterns" },
          { name: "Hooks", icon: "🪝", desc: "useState, useEffect, useContext, custom hooks" },
          { name: "React Router", icon: "🗺️", desc: "Client-side routing, nested routes" },
          { name: "State Management", icon: "🗄️", desc: "Context API, Zustand, Redux basics" },
          { name: "Tailwind CSS", icon: "💨", desc: "Utility-first styling, dark mode" },
        ],
        outcomes: [
          "Build full React applications with multiple pages",
          "Manage complex state with hooks and context",
          "Consume REST APIs and handle loading/error states",
          "Style apps with Tailwind CSS",
        ],
        outcomesKh: [
          "បង្កើត React app ពេញលេញ",
          "គ្រប់គ្រង State ជាមួយ Hooks",
          "ប្រើ REST API",
          "Style ជាមួយ Tailwind CSS",
        ],
        project: "E-commerce Product Listing — cart, filters, API integration, auth",
        projectKh: "App លក់ទំនិញ — cart, filter, auth, API",
        color: "from-sky-500 to-indigo-500",
        resources: [
          { label: "React Docs", url: "https://react.dev" },
          { label: "Tailwind CSS", url: "https://tailwindcss.com" },
        ],
      },
      {
        id: "fe-4",
        phase: 4,
        title: "Next.js & Production",
        titleKh: "Next.js & Production App",
        window: "ខែ 6–8",
        focus: "Ship production-grade apps with Next.js, performance optimization, and deployment.",
        focusKh: "បង្កើត app production ជាមួយ Next.js, SEO, Deploy",
        topics: [
          { name: "Next.js App Router", icon: "▲", desc: "SSR, SSG, ISR, layouts" },
          { name: "API Routes", icon: "🔌", desc: "Full-stack API within Next.js" },
          { name: "Authentication", icon: "🔐", desc: "NextAuth, session, JWT" },
          { name: "Web Performance", icon: "⚡", desc: "Core Web Vitals, lazy loading, CDN" },
          { name: "Testing", icon: "🧪", desc: "Jest, React Testing Library, Cypress" },
        ],
        outcomes: [
          "Build and deploy Next.js full-stack apps",
          "Implement authentication and protected routes",
          "Optimize for Core Web Vitals",
          "Write unit and integration tests",
        ],
        outcomesKh: [
          "Build & deploy Next.js app",
          "Implement authentication",
          "Optimize performance",
          "សរសេរ tests",
        ],
        project: "Full-Stack Blog Platform — auth, CRUD, SEO, deployed to Vercel",
        projectKh: "Platform Blog — auth, CRUD, SEO, deploy Vercel",
        color: "from-slate-600 to-slate-800",
        resources: [
          { label: "Next.js Docs", url: "https://nextjs.org/docs" },
          { label: "Vercel", url: "https://vercel.com" },
        ],
      },
    ],
  },
  {
    id: "backend",
    label: "Backend",
    labelKh: "ផ្នែកក្រោយ",
    tagline: "Build powerful APIs, databases, and server-side systems",
    taglineKh: "បង្កើត API, Database និង server systems ដ៏ខ្លាំង",
    icon: "⚙️",
    accent: "emerald",
    gradient: "from-emerald-600 to-teal-500",
    stages: [
      {
        id: "be-1",
        phase: 1,
        title: "Programming Fundamentals",
        titleKh: "មូលដ្ឋានភាសាកម្មវិធី",
        window: "ខែ 1–2",
        focus: "Choose Java or Python as your primary language, master core programming concepts.",
        focusKh: "ជ្រើស Java ឬ Python ហើយរៀន programming fundamentals",
        topics: [
          { name: "Java / Python", icon: "☕", desc: "OOP, data structures, algorithms" },
          { name: "Data Structures", icon: "🏗️", desc: "Arrays, lists, maps, trees" },
          { name: "Algorithms", icon: "🧮", desc: "Sorting, searching, complexity" },
          { name: "Git & CLI", icon: "🔁", desc: "Terminal, version control" },
          { name: "Linux Basics", icon: "🐧", desc: "File system, permissions, processes" },
        ],
        outcomes: [
          "Write clean, object-oriented code",
          "Implement common data structures",
          "Analyze algorithm complexity (Big O)",
          "Work comfortably in a Linux terminal",
        ],
        outcomesKh: [
          "សរសេរ code OOP ស្អាត",
          "Implement data structures",
          "យល់ Big O complexity",
          "ប្រើ Linux terminal",
        ],
        project: "CLI Task Manager — CRUD operations, file persistence, OOP design",
        projectKh: "Task Manager CLI — CRUD, save ចូល file, OOP",
        color: "from-emerald-500 to-green-400",
        resources: [
          { label: "Java Docs", url: "https://docs.oracle.com/en/java/" },
          { label: "Python Docs", url: "https://docs.python.org" },
        ],
      },
      {
        id: "be-2",
        phase: 2,
        title: "REST API Development",
        titleKh: "ការអភិវឌ្ឍ REST API",
        window: "ខែ 2–4",
        focus: "Design and build RESTful APIs with Spring Boot or Express.js.",
        focusKh: "រចនា និងបង្កើត REST API ជាមួយ Spring Boot ឬ Express.js",
        topics: [
          { name: "Spring Boot / Express", icon: "🍃", desc: "Controllers, middleware, routing" },
          { name: "REST Principles", icon: "🔌", desc: "HTTP methods, status codes, REST design" },
          { name: "Validation", icon: "✅", desc: "Input validation, error handling" },
          { name: "API Documentation", icon: "📖", desc: "Swagger / OpenAPI spec" },
          { name: "Postman Testing", icon: "📬", desc: "API testing and collections" },
        ],
        outcomes: [
          "Design RESTful APIs following best practices",
          "Build CRUD endpoints with proper status codes",
          "Validate input and handle errors gracefully",
          "Document APIs with Swagger",
        ],
        outcomesKh: [
          "Design REST API ត្រឹមត្រូវ",
          "Build CRUD endpoints",
          "Validate input, handle errors",
          "Document ជាមួយ Swagger",
        ],
        project: "Bookstore REST API — full CRUD, validation, Swagger docs, Postman tested",
        projectKh: "API Bookstore — CRUD, validation, Swagger docs",
        color: "from-teal-500 to-cyan-500",
        resources: [
          { label: "Spring Boot Docs", url: "https://spring.io/projects/spring-boot" },
          { label: "Express.js", url: "https://expressjs.com" },
        ],
      },
      {
        id: "be-3",
        phase: 3,
        title: "Databases & ORM",
        titleKh: "Database & ORM",
        window: "ខែ 4–6",
        focus: "Master SQL and NoSQL databases, and use ORMs for clean data access.",
        focusKh: "រៀន SQL, NoSQL, JPA/Prisma ORM, Database design",
        topics: [
          { name: "SQL / PostgreSQL", icon: "🗄️", desc: "Queries, joins, indexes, transactions" },
          { name: "Database Design", icon: "📐", desc: "ERD, normalization, relationships" },
          { name: "JPA / Prisma ORM", icon: "🔗", desc: "Entities, migrations, queries" },
          { name: "MongoDB", icon: "🍃", desc: "Documents, aggregations, indexes" },
          { name: "Redis", icon: "🔴", desc: "Caching, sessions, pub/sub" },
        ],
        outcomes: [
          "Design normalized relational database schemas",
          "Write complex SQL queries with joins and indexes",
          "Use ORM for database operations",
          "Implement caching with Redis",
        ],
        outcomesKh: [
          "Design database schema",
          "សរសេរ SQL queries ស្មុគស្មាញ",
          "ប្រើ ORM",
          "Implement Redis cache",
        ],
        project: "Social Media API — users, posts, comments, likes with SQL + Redis cache",
        projectKh: "API Social Media — users, posts, Redis cache",
        color: "from-blue-500 to-indigo-500",
        resources: [
          { label: "PostgreSQL Docs", url: "https://postgresql.org/docs" },
          { label: "Prisma ORM", url: "https://prisma.io" },
        ],
      },
      {
        id: "be-4",
        phase: 4,
        title: "Security & DevOps",
        titleKh: "Security & DevOps",
        window: "ខែ 6–9",
        focus: "Secure your APIs with auth, containerize with Docker, and set up CI/CD pipelines.",
        focusKh: "Secure API, Docker containers, CI/CD, Cloud deploy",
        topics: [
          { name: "JWT & OAuth2", icon: "🔐", desc: "Authentication, authorization, refresh tokens" },
          { name: "Docker", icon: "🐳", desc: "Containers, images, docker-compose" },
          { name: "CI/CD", icon: "🔄", desc: "GitHub Actions, automated testing" },
          { name: "Cloud Basics", icon: "☁️", desc: "AWS/GCP basics, VPS deployment" },
          { name: "Monitoring", icon: "📊", desc: "Logging, health checks, alerts" },
        ],
        outcomes: [
          "Implement JWT authentication and role-based access",
          "Containerize applications with Docker",
          "Set up automated CI/CD pipelines",
          "Deploy to cloud with proper monitoring",
        ],
        outcomesKh: [
          "Implement JWT authentication",
          "Containerize ជាមួយ Docker",
          "Setup CI/CD pipeline",
          "Deploy ទៅ cloud",
        ],
        project: "Production-ready E-commerce API — auth, Docker, CI/CD, deployed to VPS",
        projectKh: "API E-commerce — auth, Docker, CI/CD, deploy VPS",
        color: "from-violet-500 to-purple-600",
        resources: [
          { label: "Docker Docs", url: "https://docs.docker.com" },
          { label: "GitHub Actions", url: "https://docs.github.com/actions" },
        ],
      },
    ],
  },
  {
    id: "fullstack",
    label: "Fullstack",
    labelKh: "ពេញលេញ",
    tagline: "Master both frontend and backend to build complete applications",
    taglineKh: "រៀន Frontend + Backend ដើម្បីបង្កើត app ពេញលេញ",
    icon: "🚀",
    accent: "violet",
    gradient: "from-violet-600 to-purple-500",
    stages: [
      {
        id: "fs-1",
        phase: 1,
        title: "Foundations",
        titleKh: "មូលដ្ឋានគ្រឹះ",
        window: "ខែ 1–2",
        focus: "HTML, CSS, JavaScript and Git — the universal base for all web development.",
        focusKh: "HTML, CSS, JavaScript, Git — មូលដ្ឋានសម្រាប់ web development ទាំងអស់",
        topics: [
          { name: "HTML & CSS", icon: "🌐", desc: "Semantic markup, responsive layouts" },
          { name: "JavaScript Core", icon: "⚡", desc: "Variables, functions, DOM, events" },
          { name: "Git & GitHub", icon: "🔁", desc: "Commits, branches, pull requests" },
          { name: "Terminal / CLI", icon: "💻", desc: "File navigation, scripts, packages" },
          { name: "Deployment Basics", icon: "🌍", desc: "GitHub Pages, Netlify, Vercel" },
        ],
        outcomes: [
          "Build and deploy static websites",
          "Write basic JavaScript interactions",
          "Use Git effectively for collaboration",
          "Navigate a terminal confidently",
        ],
        outcomesKh: [
          "Build & deploy static website",
          "JavaScript interactions",
          "ប្រើ Git collaboration",
          "ប្រើ terminal",
        ],
        project: "Landing Page with interactivity — animations, form, deployed live",
        projectKh: "Landing Page — animations, form, deploy live",
        color: "from-pink-500 to-rose-500",
        resources: [
          { label: "MDN Web Docs", url: "https://developer.mozilla.org" },
          { label: "The Odin Project", url: "https://theodinproject.com" },
        ],
      },
      {
        id: "fs-2",
        phase: 2,
        title: "Frontend with React",
        titleKh: "Frontend ជាមួយ React",
        window: "ខែ 2–4",
        focus: "Build modern UIs with React, manage state, and integrate with APIs.",
        focusKh: "បង្កើត UI ជាមួយ React, State management, API integration",
        topics: [
          { name: "React + Hooks", icon: "⚛️", desc: "Components, useState, useEffect" },
          { name: "React Router", icon: "🗺️", desc: "Client-side navigation" },
          { name: "Tailwind CSS", icon: "💨", desc: "Utility-first styling" },
          { name: "API Fetching", icon: "🔌", desc: "Axios, SWR, React Query" },
          { name: "TypeScript", icon: "🔷", desc: "Types with React components" },
        ],
        outcomes: [
          "Build multi-page React applications",
          "Fetch and display API data with loading states",
          "Style with Tailwind CSS effectively",
          "Type React components with TypeScript",
        ],
        outcomesKh: [
          "Build React multi-page app",
          "Fetch API data",
          "Style ជាមួយ Tailwind",
          "TypeScript ជាមួយ React",
        ],
        project: "Movie Discovery App — React, TypeScript, TMDB API, Tailwind, deployed",
        projectKh: "App រកភាពយន្ត — React, TypeScript, API, Tailwind",
        color: "from-sky-500 to-blue-600",
        resources: [
          { label: "React Docs", url: "https://react.dev" },
          { label: "Tailwind CSS", url: "https://tailwindcss.com" },
        ],
      },
      {
        id: "fs-3",
        phase: 3,
        title: "Backend & Database",
        titleKh: "Backend & Database",
        window: "ខែ 4–7",
        focus: "Build REST APIs with Node.js, connect to PostgreSQL, and implement authentication.",
        focusKh: "REST API ជាមួយ Node.js, PostgreSQL, Authentication",
        topics: [
          { name: "Node.js / Express", icon: "🟢", desc: "REST API, middleware, routing" },
          { name: "PostgreSQL", icon: "🗄️", desc: "Schema design, queries, relations" },
          { name: "Prisma ORM", icon: "🔗", desc: "Database access, migrations" },
          { name: "JWT Auth", icon: "🔐", desc: "Register, login, protect routes" },
          { name: "File Upload", icon: "📁", desc: "Multer, cloud storage (S3/Cloudinary)" },
        ],
        outcomes: [
          "Build full REST APIs with authentication",
          "Design and query relational databases",
          "Implement JWT-based auth flows",
          "Handle file uploads to cloud storage",
        ],
        outcomesKh: [
          "Build REST API + auth",
          "Design database",
          "JWT auth flow",
          "File upload ទៅ cloud",
        ],
        project: "Social Network API — users, posts, follows, image upload, JWT auth",
        projectKh: "API Social Network — users, posts, image upload, JWT",
        color: "from-emerald-500 to-teal-500",
        resources: [
          { label: "Express.js", url: "https://expressjs.com" },
          { label: "Prisma", url: "https://prisma.io" },
        ],
      },
      {
        id: "fs-4",
        phase: 4,
        title: "Next.js Full-Stack",
        titleKh: "Next.js Full-Stack",
        window: "ខែ 7–9",
        focus: "Combine frontend and backend in one Next.js app — SSR, API routes, database.",
        focusKh: "បញ្ចូលគ្នា Frontend + Backend ក្នុង Next.js app",
        topics: [
          { name: "Next.js App Router", icon: "▲", desc: "SSR, SSG, ISR, layouts, streaming" },
          { name: "Server Actions", icon: "⚡", desc: "Mutations without API routes" },
          { name: "NextAuth.js", icon: "🔐", desc: "OAuth, credentials, sessions" },
          { name: "Prisma + PostgreSQL", icon: "🗄️", desc: "Full-stack data layer" },
          { name: "Deployment", icon: "☁️", desc: "Vercel, Railway, environment vars" },
        ],
        outcomes: [
          "Build complete full-stack Next.js applications",
          "Implement SSR and SSG for optimal performance",
          "Add OAuth authentication with NextAuth",
          "Deploy full-stack apps to production",
        ],
        outcomesKh: [
          "Full-stack Next.js app",
          "SSR/SSG optimization",
          "OAuth ជាមួយ NextAuth",
          "Deploy production",
        ],
        project: "SaaS Dashboard — auth, subscriptions, CRUD, analytics, deployed to Vercel",
        projectKh: "SaaS Dashboard — auth, CRUD, analytics, Vercel",
        color: "from-violet-600 to-purple-600",
        resources: [
          { label: "Next.js Docs", url: "https://nextjs.org/docs" },
          { label: "NextAuth.js", url: "https://next-auth.js.org" },
        ],
      },
      {
        id: "fs-5",
        phase: 5,
        title: "DevOps & Launch",
        titleKh: "DevOps & Launch",
        window: "ខែ 9–12",
        focus: "Containerize, automate, monitor, and launch production-grade applications.",
        focusKh: "Docker, CI/CD, Monitoring, Launch production app",
        topics: [
          { name: "Docker", icon: "🐳", desc: "Containers, multi-stage builds, compose" },
          { name: "CI/CD Pipelines", icon: "🔄", desc: "GitHub Actions, automated tests" },
          { name: "Nginx", icon: "🌐", desc: "Reverse proxy, SSL, load balancing" },
          { name: "Monitoring", icon: "📊", desc: "Logs, health checks, error tracking" },
          { name: "Portfolio Polish", icon: "💼", desc: "README, case studies, LinkedIn" },
        ],
        outcomes: [
          "Containerize full-stack apps with Docker",
          "Automate testing and deployment with CI/CD",
          "Configure Nginx as a reverse proxy",
          "Ship a polished portfolio to land your first job",
        ],
        outcomesKh: [
          "Containerize ជាមួយ Docker",
          "CI/CD automation",
          "Nginx configuration",
          "Portfolio ពេញលេញ ដើម្បីរក job",
        ],
        project: "Production Portfolio Platform — Dockerized, CI/CD, custom domain, monitored",
        projectKh: "Portfolio Platform — Docker, CI/CD, domain ផ្ទាល់ខ្លួន",
        color: "from-rose-500 to-pink-600",
        resources: [
          { label: "Docker Docs", url: "https://docs.docker.com" },
          { label: "GitHub Actions", url: "https://docs.github.com/actions" },
        ],
      },
    ],
  },
];